version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.3.4
            bundle install
      - run:
          name: Rspec
          command: |
            bundle exec rspec --format doc --format RspecJunitFormatter -o spec/reports/rspec.xml
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop --format progress --format junit --out spec/reports/rubocop.xml
      - store_test_results:
          path: spec/reports/
